import { APPRENANTS_REELS as FICHE_APPRENANTS } from '../data/mockApprenants_reels';
import { FICHE_ENTREPRISES } from '../data/mockEntreprises';

const CFA = {
  raisonSociale: 'PAM OI Formation',
  siret: '881 279 392 00016',
  telephone: '0693 55 64 92',
  email: 'pamelamaillot@pamoi.re',
  directeur: 'Paméla MAILLOT',
};

export function assemblerDonnees(
  apprenantId: string,
  entrepriseId: string,
  champsSupplementaires?: Record<string, string>
): Record<string, string> {
  const a = FICHE_APPRENANTS[apprenantId];
  const e = FICHE_ENTREPRISES[entrepriseId];

  const civilite = a?.sexe === 'Féminin' ? 'Mme' : 'M.';
  const nomComplet = a ? `${a.prenom} ${a.nom}` : '';

  return {
    CFA_RAISON_SOCIALE: CFA.raisonSociale,
    CFA_SIRET: CFA.siret,
    CFA_TELEPHONE: CFA.telephone,
    CFA_EMAIL: CFA.email,
    CFA_DIRECTRICE: CFA.directeur,
    LIEU_FORMATION: '1 Chemin Dubuisson 97436 Saint-Leu',
    APPRENANT_CIVILITE: civilite,
    APPRENANT_NOM: a?.nom ?? '',
    APPRENANT_PRENOM: a?.prenom ?? '',
    APPRENANT_NOM_COMPLET: nomComplet,
    APPRENANT_DATE_NAISSANCE: a?.dateNaissance ?? '',
    APPRENANT_LIEU_NAISSANCE: a?.communeNaissance ?? '',
    APPRENANT_ADRESSE: a?.adresse ?? '',
    APPRENANT_CP: a?.codePostal ?? '',
    APPRENANT_VILLE: a?.ville ?? '',
    APPRENANT_TELEPHONE: a?.telephone ?? '',
    APPRENANT_EMAIL: a?.email ?? '',
    REPRESENTANT_LEGAL_NOM: a?.responsableLegal?.nom ?? '',
    REPRESENTANT_LEGAL_PRENOM: a?.responsableLegal?.prenom ?? '',
    REPRESENTANT_LEGAL_LIEN: a?.responsableLegal?.lien ?? '',
    REPRESENTANT_LEGAL_ADRESSE: a?.adresse ?? '',
    REPRESENTANT_LEGAL_TELEPHONE: a?.responsableLegal?.telephone ?? '',
    REPRESENTANT_LEGAL_EMAIL: a?.responsableLegal?.email ?? '',
    FORMATION_LIBELLE: a?.formation ?? '',
    DATE_DEBUT_FORMATION: a?.dateDebut ?? '',
    DATE_FIN_FORMATION: a?.dateFin ?? '',
    DATE_DEBUT_CONTRAT: a?.dateDebut ?? '',
    DATE_FIN_CONTRAT: a?.dateFin ?? '',
    DUREE_FORMATION: '12 mois',
    VOLUME_HORAIRE_TOTAL: '490 h',
    COUT_TOTAL_FRAIS_PEDAGOGIQUES: '4 900 €',
    ENTREPRISE_RAISON_SOCIALE: e?.nom ?? a?.entreprise ?? '',
    SIRET_ENTREPRISE: e?.siret ?? '',
    ADRESSE_ENTREPRISE: e?.adresse ?? '',
    Code_Postal_ENTREPRISE: e?.codePostal ?? '',
    Ville_ENTREPRISE: e?.ville ?? '',
    ACTIVITE_ENTREPRISE: e?.cerfa?.libelleAPE ?? '',
    IDCC_ENTREPRISE: e?.cerfa?.idcc ?? '',
    OPCO: e?.cerfa?.opco ?? '',
    DIRIGEANT_NOM_COMPLET: e?.tuteurs?.[0]?.nom ?? '',
    QUALITE_SIGNATAIRE_ENTREPRISE: 'Gérant',
    TUTEUR_NOM_COMPLET: a?.tuteur ?? '',
    POSTE_TUTEUR: e?.tuteurs?.[0]?.fonction ?? '',
    Mail_TUTEUR: a?.emailTuteur ?? '',
    'N° Tel_TUTEUR': a?.telephoneTuteur ?? '',
    MAITRE_APPRENTISSAGE_NOM_COMPLET: a?.tuteur ?? '',
    MAITRE_APPRENTISSAGE_TELEPHONE: a?.telephoneTuteur ?? '',
    MAITRE_APPRENTISSAGE_EMAIL: a?.emailTuteur ?? '',
    N_DECA: '',
    DATE_SIGNATURE_DOC: new Date().toLocaleDateString('fr-FR'),
    CR_DATE_DEBUT: a?.dateDebut ?? '',
    CR_DATE_FIN: a?.dateFin ?? '',
    CR_DUREE_MOIS: '12',
    DATE_FIN_MAINTIEN: '',
    DATE_RUPTURE_CONTRAT: '',
    LIEU_SIGNATURE_DOC: 'Saint-Leu',
    RNCP_CODE: 'À compléter',
    IDCC_CODE: a?.cerfa?.idcc ?? '',
    COUT_PEDAGOGIQUE_ANNEE_1: '4 900 €',
    COUT_PEDAGOGIQUE_ANNEE_2: '',
    COUT_TOTAL_FRAIS_PEDAGOGIQUES: '4 900 €',
    DATE_FIN_PREMIERE_ANNEE: '30/04/2027',
    DATE_DEBUT_DEUXIEME_ANNEE: '',
    TOTAL_JOURS_PREMIERE_ANNEE: '245',
    TOTAL_JOURS_DEUXIEME_ANNEE: '',
    FRAIS_ANNEXES_REPAS_ANNEE_1: '0',
    FRAIS_ANNEXES_REPAS_ANNEE_2: '0',
    'Nombre_repas_ 1': '0',
    'Nombre_repas_ 2': '0',
    FRAIS_PREMIER_EQUIPEMENT: '0',
    TOTAL_FRAIS_ANNEXES: '0',
    APPRENANT_NOM_COMPLET: nomComplet,
    ENTREPRISE_SIRET: e?.siret ?? '',
    ENTREPRISE_ACTIVITE: e?.cerfa?.libelleAPE ?? '',
    ENTREPRISE_ADRESSE: e?.adresse ?? '',
    ENTREPRISE_CP: e?.codePostal ?? '',
    ENTREPRISE_VILLE: e?.ville ?? '',
    CR_LIEU_SIGNATURE: 'Saint-Leu',
    CR_SIGNATAIRE_QUALITE: 'Directrice',
    CR_DUREE_HEURES: '490 heures',
    REFERENT_APPRENTI_NOM_COMPLET: 'Betty REBOUL',
    REFERENT_APPRENTI_TELEPHONE: '0693 55 64 97',
    REFERENT_APPRENTI_EMAIL: 'pedagogie@pamoi.re',
    ...champsSupplementaires,
  };
}